name: Deploy Docker WebApp to EC2

on:
  push:
    branches: [ "main" ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t mywebapp1:latest .

    - name: Save Docker image
      run: |
        docker save mywebapp1:latest -o mywebapp1.tar
        chmod 644 mywebapp1.tar

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "mywebapp1.tar"
        target: "~/"

    - name: Run Docker container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i ~/mywebapp1.tar
          docker stop mywebapp1 || true
          docker rm mywebapp1 || true
          docker run -d --name mywebapp1 -p 8086:80 mywebapp1:latest
